name = "ip"
main = "entry.py"
compatibility_date = "2024-03-20"
compatibility_flags = ["python_workers"]
[observability]
[observability.logs]
enabled = true
invocation_logs = true
# Add this section to serve static files
[assets]
directory = "assets"
binding = "ASSETS"